#server port
server:
  port: 8890
#application name
spring:
  application:
    name: FILE-SERVICE
#it is a eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost